from django.core.management import BaseCommand

from apps.home.models import *


class Command(BaseCommand):
    help = 'Init data'

    def handle(self, *args, **options):
        Doingame(ten="Đá 7", gia_tien_xu=80, gia_tien_atm=3, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=0).save()
        Doingame(ten="Đá 8", gia_tien_xu=300, gia_tien_atm=10, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=1).save()
        Doingame(ten="Đá 9", gia_tien_xu=1500, gia_tien_atm=40, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=2).save()
        Doingame(ten="Đá 10", gia_tien_xu=4700, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=3).save()
        Doingame(ten="Heo random", gia_tien_xu=2000, gia_tien_atm=80, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=4).save()
        Doingame(ten="Heo lv100", gia_tien_xu=20000, gia_tien_atm=1000, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=5).save()
        Doingame(ten="Kinh nghiệm thú", gia_tien_xu=1000, gia_tien_atm=35, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=6).save()
        Doingame(ten="Lệnh bài gia tộc", gia_tien_xu=50, gia_tien_atm=2, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=7).save()
        Doingame(ten="Hoán tinh thạch", gia_tien_xu=400, gia_tien_atm=15, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=8).save()
        Doingame(ten="Túi vai 3", gia_tien_xu=150, gia_tien_atm=5, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=9).save()
        Doingame(ten="Mảnh bản đồ", gia_tien_xu=20, gia_tien_atm=1, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=10).save()
        Doingame(ten="Sách tiềm năng", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=11).save()
        Doingame(ten="Sách kỹ năng", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=12).save()
        Doingame(ten="Bánh tiềm năng", gia_tien_xu=1200, gia_tien_atm=40, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=13).save()
        Doingame(ten="Bánh kỹ năng", gia_tien_xu=400, gia_tien_atm=20, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=14).save()
        Doingame(ten="Đan tấn công", gia_tien_xu=25, gia_tien_atm=1, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=15).save()
        Doingame(ten="Đan HP", gia_tien_xu=20, gia_tien_atm=1, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=16).save()
        Doingame(ten="Thức ăn 4x", gia_tien_xu=300, gia_tien_atm=10, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=17).save()
        Doingame(ten="Thức ăn 5x", gia_tien_xu=300, gia_tien_atm=10, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=18).save()
        Doingame(ten="Thức ăn 6x", gia_tien_xu=300, gia_tien_atm=10, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=19).save()
        Doingame(ten="Quạt 4x mcs", gia_tien_xu=4000, gia_tien_atm=120, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=20).save()
        Doingame(ten="Tiêu 4x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=21).save()
        Doingame(ten="Đao 4x mcs", gia_tien_xu=3000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=22).save()
        Doingame(ten="Kiếm 4x mcs", gia_tien_xu=4000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=23).save()
        Doingame(ten="Kunai 4x mcs", gia_tien_xu=4000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=24).save()
        Doingame(ten="Cung 4x mcs", gia_tien_xu=4000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=25).save()
        Doingame(ten="Quạt 5x mcs", gia_tien_xu=4000, gia_tien_atm=120, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=26).save()
        Doingame(ten="Tiêu 5x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=27).save()
        Doingame(ten="Đao 5x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=28).save()
        Doingame(ten="Kiếm 5x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=29).save()
        Doingame(ten="Kunai 5x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=30).save()
        Doingame(ten="Cung 5x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=31).save()
        Doingame(ten="Đao 5x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=32).save()
        Doingame(ten="Quạt 6x mcs", gia_tien_xu=4000, gia_tien_atm=120, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=33).save()
        Doingame(ten="Tiêu 6x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=34).save()
        Doingame(ten="Đao 6x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=35).save()
        Doingame(ten="Kiếm 6x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=36).save()
        Doingame(ten="Kunai 6x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=37).save()
        Doingame(ten="Cung 6x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=38).save()
        Doingame(ten="Đao 6x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=39).save()
        Doingame(ten="Quạt 7x mcs", gia_tien_xu=4000, gia_tien_atm=120, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=40).save()
        Doingame(ten="Tiêu 7x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=41).save()
        Doingame(ten="Đao 7x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=42).save()
        Doingame(ten="Kiếm 7x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=43).save()
        Doingame(ten="Kunai 7x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=44).save()
        Doingame(ten="Cung 7x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=45).save()
        Doingame(ten="Đao 7x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=46).save()
        Doingame(ten="Quạt 8x mcs", gia_tien_xu=4000, gia_tien_atm=120, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=47).save()
        Doingame(ten="Tiêu 8x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=48).save()
        Doingame(ten="Đao 8x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=49).save()
        Doingame(ten="Kiếm 8x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=50).save()
        Doingame(ten="Kunai 8x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=51).save()
        Doingame(ten="Cung 8x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=52).save()
        Doingame(ten="Đao 8x mcs", gia_tien_xu=5000, gia_tien_atm=150, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=53).save()
        Doingame(ten="Sách võ công quạt 6x", gia_tien_xu=100, gia_tien_atm=5, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=54).save()
        Doingame(ten="Sách võ công đao 6x", gia_tien_xu=100, gia_tien_atm=5, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=55).save()
        Doingame(ten="Sách võ công tiêu 6x", gia_tien_xu=100, gia_tien_atm=5, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=56).save()
        Doingame(ten="Sách võ công kiếm 6x", gia_tien_xu=100, gia_tien_atm=5, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=57).save()
        Doingame(ten="Sách võ công kunai 6x", gia_tien_xu=100, gia_tien_atm=5, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=58).save()
        Doingame(ten="Sách võ công cung 6x", gia_tien_xu=100, gia_tien_atm=5, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=59).save()
        Doingame(ten="Sách võ công quạt 7x", gia_tien_xu=150, gia_tien_atm=5, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=60).save()
        Doingame(ten="Sách võ công đao 7x", gia_tien_xu=150, gia_tien_atm=5, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=61).save()
        Doingame(ten="Sách võ công tiêu 7x", gia_tien_xu=150, gia_tien_atm=5, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=62).save()
        Doingame(ten="Sách võ công kiếm 7x", gia_tien_xu=150, gia_tien_atm=5, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=63).save()
        Doingame(ten="Sách võ công kunai 7x", gia_tien_xu=150, gia_tien_atm=5, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=64).save()
        Doingame(ten="Sách võ công cung 7x", gia_tien_xu=150, gia_tien_atm=5, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=65).save()
        Doingame(ten="Sách võ công quạt 8x", gia_tien_xu=200, gia_tien_atm=7, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=66).save()
        Doingame(ten="Sách võ công đao 8x", gia_tien_xu=200, gia_tien_atm=7, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=67).save()
        Doingame(ten="Sách võ công tiêu 8x", gia_tien_xu=200, gia_tien_atm=7, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=68).save()
        Doingame(ten="Sách võ công kiếm 8x", gia_tien_xu=200, gia_tien_atm=7, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=69).save()
        Doingame(ten="Sách võ công kunai 8x", gia_tien_xu=200, gia_tien_atm=7, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=70).save()
        Doingame(ten="Sách võ công cung 8x", gia_tien_xu=200, gia_tien_atm=7, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=71).save()
        Doingame(ten="Đồ mcs 4x (Nam)", gia_tien_xu=500, gia_tien_atm=20, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=72).save()
        Doingame(ten="Đồ mcs 5x (Nam)", gia_tien_xu=500, gia_tien_atm=20, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=73).save()
        Doingame(ten="Đồ mcs 6x (Nam)", gia_tien_xu=500, gia_tien_atm=20, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=74).save()
        Doingame(ten="Đồ mcs 7x (Nam)", gia_tien_xu=500, gia_tien_atm=20, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=75).save()
        Doingame(ten="Đồ mcs 4x (Nữ)", gia_tien_xu=500, gia_tien_atm=20, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=76).save()
        Doingame(ten="Đồ mcs 5x (Nữ)", gia_tien_xu=500, gia_tien_atm=20, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=77).save()
        Doingame(ten="Đồ mcs 6x (Nữ)", gia_tien_xu=500, gia_tien_atm=20, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=78).save()
        Doingame(ten="Đồ mcs 7x (Nữ)", gia_tien_xu=500, gia_tien_atm=20, so_luong=100, trang_thai=1, thong_tin="sv2", sap_xep=79).save()
        Doingame(ten="HP 1x", gia_tien_xu=1, gia_tien_atm=0.1, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=80).save()
        Doingame(ten="HP 3x", gia_tien_xu=3, gia_tien_atm=0.1, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=80).save()
        Doingame(ten="HP 5x", gia_tien_xu=6, gia_tien_atm=0.1, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=80).save()
        Doingame(ten="HP 7x", gia_tien_xu=8, gia_tien_atm=0.1, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=80).save()
        Doingame(ten="MP 1x", gia_tien_xu=1, gia_tien_atm=0.1, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=80).save()
        Doingame(ten="MP 3x", gia_tien_xu=3, gia_tien_atm=0.1, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=80).save()
        Doingame(ten="MP 5x", gia_tien_xu=6, gia_tien_atm=0.1, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=80).save()
        Doingame(ten="MP 7x", gia_tien_xu=8, gia_tien_atm=0.1, so_luong=100, trang_thai=1, thong_tin="sv2",sap_xep=80).save()


