# Generated by Django 3.2.6 on 2022-02-24 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DichVuGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('gia_tien_xu', models.FloatField()),
                ('gia_tien_atm', models.FloatField()),
                ('trang_thai', models.SmallIntegerField(default=1)),
                ('thong_tin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doingame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('gia_tien_xu', models.FloatField()),
                ('gia_tien_atm', models.FloatField()),
                ('so_luong', models.FloatField()),
                ('trang_thai', models.SmallIntegerField(default=1)),
                ('thong_tin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thong_tin', models.CharField(max_length=255)),
                ('gia_tien_xu', models.FloatField()),
                ('gia_tien_atm', models.FloatField()),
                ('soluong', models.FloatField()),
                ('trang_thai', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GiaoDich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hoa_don', models.IntegerField()),
                ('ngay_gio_giao_dich', models.DateTimeField(auto_now=True)),
                ('thong_tin', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
