# Generated by Django 3.2.6 on 2022-02-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220224_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaodich',
            name='so_luong',
            field=models.IntegerField(default=0),
        ),
    ]
