# Generated by Django 3.2.6 on 2022-02-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_giaodich_so_luong'),
    ]

    operations = [
        migrations.AddField(
            model_name='doingame',
            name='sap_xep',
            field=models.IntegerField(default=0),
        ),
    ]
